#!/bin/bash

# Use the following commands to create a key-pair!
# Generate public-private key pair:
#   openssl genrsa -out keyfile.key 4096
# Extract public key:
#   openssl rsa -in keyfile.key -pubout -out keyfile.pub

readonly ConfigFile=/etc/sbbs
readonly Dependencies="tar awk grep sort"
readonly TargetPattern="[A-Z]([a-z][A-Z])*"
readonly DateInfoPattern="[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}"
readonly FileExtensionPattern="\.tar\.gz"
readonly BackupFilePattern="${TargetPattern}_at_${DateInfoPattern}${FileExtensionPattern}"



# Checks if every program in a given list is installed and crashes the script
# if one isn't.
# Args:
#   $1 - String - Space seperated list of program names
check_installed_progs(){
  # Check if required programms are installed.
  required_progs=$1
  for required_prog in ${required_progs}
  do
    # Use the command command to check if the required program is missing.
    if ! command -v ${required_prog} &> /dev/null
    then
      echo "The command $required_prog could not be found. Please make sure it is installed!"
      exit 1
    fi
  done
}


# Get all backup files of a given target in a given backup destination
# Args:
#   $1 - String - The backup dest path.
#   $2 - String - Name of the target.
get_backups(){
  echo "$(ls $1 | grep  -E "$2_at_${DateInfoPattern}${FileExtensionPattern}")"
}

# Sort backup file names by the date part.
# Args:
#   $1 - String - A newline seperated list of filenames
sort_backups(){
  echo "$(echo "$1"  | awk -F'[_\\-.]' '{print $3 $4 $5 $6 $7 $8, $0}' | sort -n | awk -F' ' '{print $2}')"
}


# Count how many backup files of a given target exist in a given location and
# then remove all except for the newest x ones.
# Args:
#   $1 - String - The backup dest path.
#   $2 - String - Target Name.
#   $3 - Int - Count of backups to keep.
remove_old_backups(){
  backups=$(sort_backups "$(get_backups $1 $2)")
  cnt_backups=$(echo "$backups" | wc -l)
  readarray -d "\n" backups <<< $(echo "$backups")
  
  for backup in $backups
  do
    if [[ ${cnt_backups} -gt $3 ]]
    then
      rm "$1/${backup}"
      let "cnt_backups=cnt_backups-1"
    fi 
  done
}

# Generates a symmetric key, then uses it to encrypt a given file then it
# encrypts the symmetric key using a given public key and stores the given file
# together with the encrypted key into a tar with the given name.
# Args:
#   $1 - String - The file to encrypt.
#   $2 - String - The public key file.
#   $3 - String - The name of the resulting file.
encrypt_file(){
  # Generate a random symmetric key
  openssl rand 256 > /tmp/symmetric_key

  # Use symmetric key to encrypt file 
  openssl enc -aes-256-cbc -pbkdf2 -salt -out /tmp/file.enc -pass file:/tmp/symmetric_key -in $1

  # Use public key to encrypt symmetric key
  openssl pkeyutl -encrypt -pubin -inkey $2 -in /tmp/symmetric_key -out /tmp/key.enc

  # Remove unencryped symmetric key
  rm /tmp/symmetric_key

  # Now move the key and the file into a new tar
  echo "Now zipping to location $3"
  tar -cjf "$3" -C /tmp "file.enc" "key.enc" --force-local

  rm /tmp/file.enc /tmp/key.enc
}

# Check if config exists.
if [ ! -f "$ConfigFile" ]; then
  echo "Config File at '${ConfigFile}' does not exist!"
  exit 1
fi


check_installed_progs ${Dependencies}


# Load Config
source ${ConfigFile}

# Check if public key exists.
if [ ! -f "$PublicKey" ]; then
  echo "Public key at '${PublicKey}' does not exist!"
  exit 1
fi

# Check if backup target exists
if [ ! -d "$BackupTarget" ]; then
  echo "Backup target '${BackupTarget}' does not exist!"
  exit 1
fi

oldIFS=${IFS}
IFS=" "

# Use tr command to replace the delimiter character with a newline
read -ra backup_names <<< "$BackupNames"
read -ra backup_sources <<< "$BackupSources"

IFS=${oldIFS}


# For each Target start compressing and moving the new backup into the location
# and then deleting the old ones.

for ((i=0;i < ${#backup_names[@]}; i++))
do
  # Check if backup source exists
  if [ ! -f "${backup_sources[$i]}" ]; then
    echo "Backup source '${backup_sources[$i]}' does not exist!"
    continue 
  fi

  echo "Backup '${backup_names[$i]}' started."
  echo "Zipping '${backup_sources[$i]}'."
  
  # Create the new name of the tarball
  printf -v date '%(%Y-%m-%d_%H-%M-%S)T' -1 # Get the current date and time
  tarball_name="${backup_names[$i]}_at_${date}"
  
  # Compress the backup target 
  # Use the -C option to run the command from the root directory!
  tar -czf /tmp/data.tar.gz -C / ${backup_sources[$i]} &> /dev/null 
  
  encrypt_file "/tmp/data.tar.gz" ${PublicKey} ${BackupTarget}/${tarball_name}.tar.gz

  rm /tmp/data.tar.gz

 #tar -czf ${BackupTarget}/${tarball_name}.tar.gz -C / ${backup_sources[$i]} &> /dev/null
  
  echo "Cleaning old backups." 
  remove_old_backups ${BackupTarget} ${backup_names[$i]} ${BackupCount} 

  echo ""
done
